### ISSUE TITLE
API research

### ISSUE THREAD

**Issue by TaylorStrubhar** [TaylorStrubhar/dogs-dogs-dogs#4]
```
find out if we can use API in any unexpected way, maybe not random?
make sure the autofill feature will work as we expect
help with fetch function/scripting
```

**Comment by josephkurpierz** [comment]
Dog pics can be posted, but right now breed name is hard coded.  Will need to tie into search bar results
Breed list is retrieved for potential use with validated autofill in search bar.
**Dog facts API is giving me error 301.  It seems like it is for "permanently moved" and I don't know if there is a work around without installing 3rd party look up options for redirects.  Sounds complicated.**

**Comment by TaylorStrubhar** [comment]
Do we want to find a different API then to replace the facts part?
